import { Router, Request, Response } from 'express';
import { authenticatePassword, bootstrapTokenUser, createUserSession, destroySession, generateToken, getSessionPrincipal, parseCookies, recordLogin, revokeSessionsForUser, tokenConfigured, verifyToken } from '../auth';
import { SESSION_TTL_MS } from '../auth-session';
import { createUser, getStoredTotpSecret, listUsers, setTotpEnabled, setUserEnabled, setUserPassword, setUserRole, stageTotpSecret, validatePassword, validateUsername, type AuthUser } from '../auth-users';
import { audit, hasPermission } from '../security';
import { buildOtpAuthUri, generateTotpSecret, revealTotpSecret, verifyTotp } from '../totp';
import { clearLoginFailures, loginBlocked, loginKey, recordLoginFailure } from '../auth-abuse';

export const router = Router();
function setSessionCookie(req:Request,res:Response,session:string,maxAgeSeconds:number):void{const forwardedProto=req.get('x-forwarded-proto');const secure=req.secure||forwardedProto==='https';res.setHeader('Set-Cookie',`session=${encodeURIComponent(session)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAgeSeconds}${secure?'; Secure':''}`);}
function noStore(res:Response):void{res.setHeader('Cache-Control','no-store');}
function currentPrincipal(req:Request){const cookies=parseCookies(req.headers.cookie||'');return cookies.session?getSessionPrincipal(cookies.session):null;}
function requireAdmin(req:Request,res:Response):boolean{const principal=currentPrincipal(req);if(!principal){res.status(401).json({error:'authenticated session required'});return false;}if(!hasPermission(principal.role,'policy.manage')){res.status(403).json({error:'admin permission required'});return false;}return true;}
function publicUser(user:AuthUser):object{return{id:user.id,username:user.username,role:user.role,enabled:user.enabled,mfaEnabled:user.totpEnabled,createdAt:user.createdAt,updatedAt:user.updatedAt,lastLoginAt:user.lastLoginAt};}
function verifyTotpForUser(userId:string,otp:string):boolean{const encrypted=getStoredTotpSecret(userId);if(!encrypted)return false;try{return verifyTotp(revealTotpSecret(encrypted),otp);}catch{return false;}}
function requireMfa(user:AuthUser,otp:unknown):boolean{if(!user.totpEnabled)return true;return typeof otp==='string'&&verifyTotpForUser(user.id,otp);}

router.post('/login',(req:Request,res:Response)=>{noStore(res);const body=(req.body||{}) as {token?:string;username?:string;password?:string;otp?:string};const presented=typeof body.username==='string'&&body.username?body.username:(typeof body.token==='string'&&body.token?'token':'unknown');const key=loginKey(presented,req.ip||'unknown');const blocked=loginBlocked(key);if(blocked){res.setHeader('Retry-After',String(blocked));res.status(429).json({error:'too many authentication failures',retryAfter:blocked});return;}let user:AuthUser|null=null;if(typeof body.token==='string'&&body.token){if(!verifyToken(body.token)){const result=recordLoginFailure(key);if(result.locked)res.setHeader('Retry-After',String(result.retryAfter));res.status(result.locked?429:401).json({error:'Invalid access token'});return;}user=bootstrapTokenUser();}else if(typeof body.username==='string'&&typeof body.password==='string'){user=authenticatePassword(body.username,body.password);if(!user){const result=recordLoginFailure(key);if(result.locked)res.setHeader('Retry-After',String(result.retryAfter));res.status(result.locked?429:401).json({error:'Invalid username or password'});return;}}else{res.status(400).json({error:'provide either token or username/password'});return;}if(!requireMfa(user,body.otp)){const result=recordLoginFailure(key);if(result.locked)res.setHeader('Retry-After',String(result.retryAfter));res.status(result.locked?429:401).json(result.locked?{error:'too many authentication failures',retryAfter:result.retryAfter}:{error:'mfa_required',method:'totp'});return;}clearLoginFailures(key);user=recordLogin(user.id);const session=createUserSession(user);setSessionCookie(req,res,session,Math.floor(SESSION_TTL_MS/1000));audit(`user:${user.id}`,'auth.login',user.id,'allow',{username:user.username,role:user.role,mfa:user.totpEnabled});res.json({ok:true,user:publicUser(user)});});

router.post('/logout',(req:Request,res:Response)=>{noStore(res);const cookies=parseCookies(req.headers.cookie||'');if(cookies.session)destroySession(cookies.session);setSessionCookie(req,res,'',0);res.json({ok:true});});
router.get('/status',(req:Request,res:Response)=>{noStore(res);const principal=currentPrincipal(req);if(!principal){res.status(401).json({configured:tokenConfigured(),authenticated:false});return;}res.json({configured:tokenConfigured(),authenticated:true,actor:principal.actor,userId:principal.userId,username:principal.username,role:principal.role});});
router.post('/rotate',(req:Request,res:Response)=>{noStore(res);if(!requireAdmin(req,res))return;const principal=currentPrincipal(req)!;const raw=generateToken();audit(principal.actor,'auth.token.rotated',principal.userId,'allow');res.json({token:raw});});
router.get('/users',(req:Request,res:Response)=>{noStore(res);if(!requireAdmin(req,res))return;res.json({users:listUsers().map(publicUser)});});
router.post('/users',(req:Request,res:Response)=>{noStore(res);if(!requireAdmin(req,res))return;const principal=currentPrincipal(req)!;const body=(req.body||{}) as {username?:string;password?:string;role?:AuthUser['role']};try{if(typeof body.username!=='string'||typeof body.password!=='string'||typeof body.role!=='string')throw new Error('username, password and role are required');const username=validateUsername(body.username);validatePassword(body.password);const result=createUser(username,body.password,body.role);audit(principal.actor,'auth.user.created',result.user.id,'allow',{username:result.user.username,role:result.user.role});res.status(201).json({user:publicUser(result.user)});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
router.patch('/users/:id/role',(req:Request,res:Response)=>{noStore(res);if(!requireAdmin(req,res))return;const principal=currentPrincipal(req)!;try{const user=setUserRole(req.params.id,(req.body||{}).role as AuthUser['role']);revokeSessionsForUser(user.id);audit(principal.actor,'auth.user.role_changed',user.id,'allow',{role:user.role});res.json({user:publicUser(user)});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
router.patch('/users/:id/enabled',(req:Request,res:Response)=>{noStore(res);if(!requireAdmin(req,res))return;const principal=currentPrincipal(req)!;try{const enabled=(req.body||{}).enabled;if(typeof enabled!=='boolean')throw new Error('enabled must be boolean');const user=setUserEnabled(req.params.id,enabled);if(!enabled)revokeSessionsForUser(user.id);audit(principal.actor,'auth.user.enabled_changed',user.id,'allow',{enabled:user.enabled});res.json({user:publicUser(user)});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
router.patch('/users/:id/password',(req:Request,res:Response)=>{noStore(res);const principal=currentPrincipal(req);if(!principal){res.status(401).json({error:'authenticated session required'});return;}const isAdmin=hasPermission(principal.role,'policy.manage'),isSelf=principal.userId===req.params.id;if(!isAdmin&&!isSelf){res.status(403).json({error:'admin permission required'});return;}try{const password=(req.body||{}).password;if(typeof password!=='string')throw new Error('password is required');const user=setUserPassword(req.params.id,password);revokeSessionsForUser(user.id);audit(principal.actor,'auth.user.password_changed',user.id,'allow');res.json({ok:true});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
router.post('/users/:id/mfa/totp/enroll',(req:Request,res:Response)=>{noStore(res);const principal=currentPrincipal(req);if(!principal){res.status(401).json({error:'authenticated session required'});return;}const isAdmin=hasPermission(principal.role,'policy.manage'),isSelf=principal.userId===req.params.id;if(!isAdmin&&!isSelf){res.status(403).json({error:'admin permission required'});return;}try{const user=listUsers().find(candidate=>candidate.id===req.params.id);if(!user)throw new Error('user not found');const secret=generateTotpSecret();stageTotpSecret(user.id,secret);audit(principal.actor,'auth.mfa.totp.enrollment_staged',user.id,'allow');res.json({userId:user.id,username:user.username,secret,otpauthUri:buildOtpAuthUri(user.username,secret),enabled:false});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
router.post('/users/:id/mfa/totp/confirm',(req:Request,res:Response)=>{noStore(res);const principal=currentPrincipal(req);if(!principal){res.status(401).json({error:'authenticated session required'});return;}const isAdmin=hasPermission(principal.role,'policy.manage'),isSelf=principal.userId===req.params.id;if(!isAdmin&&!isSelf){res.status(403).json({error:'admin permission required'});return;}try{const otp=(req.body||{}).otp,encrypted=getStoredTotpSecret(req.params.id);if(typeof otp!=='string'||!encrypted||!verifyTotp(revealTotpSecret(encrypted),otp))throw new Error('invalid TOTP code');const user=setTotpEnabled(req.params.id,true);audit(principal.actor,'auth.mfa.totp.enabled',user.id,'allow');res.json({user:publicUser(user)});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
router.post('/users/:id/mfa/totp/disable',(req:Request,res:Response)=>{noStore(res);const principal=currentPrincipal(req);if(!principal){res.status(401).json({error:'authenticated session required'});return;}if(!hasPermission(principal.role,'policy.manage')){res.status(403).json({error:'admin permission required'});return;}try{const user=setTotpEnabled(req.params.id,false);revokeSessionsForUser(user.id);audit(principal.actor,'auth.mfa.totp.disabled',user.id,'allow');res.json({user:publicUser(user)});}catch(error){res.status(400).json({error:String((error as Error).message)});}});
