import { getDb, nowIso, randomId } from './db';
import { audit, type SecurityContext, type RiskLevel, riskDecision } from './security';

export type NextAction = 'continue'|'branch'|'retry'|'approval_required'|'stop';
export interface ExecutionFeedback { taskId:string; missionId:string; ok:boolean; status:string; findingCount?:number; evidenceCount?:number; retryable?:boolean; recommendedCapabilities?:string[]; reason?:string; }
export interface AdaptiveDecision { id:string; action:NextAction; reason:string; capabilities:string[]; approvalRequired:boolean; }
export function initAdaptiveSchema(){getDb().exec(`CREATE TABLE IF NOT EXISTS execution_feedback(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,mission_id TEXT NOT NULL,ok INTEGER NOT NULL,status TEXT NOT NULL,finding_count INTEGER NOT NULL DEFAULT 0,evidence_count INTEGER NOT NULL DEFAULT 0,retryable INTEGER NOT NULL DEFAULT 0,recommended_json TEXT NOT NULL DEFAULT '[]',reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS adaptive_decisions(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,task_id TEXT NOT NULL,action TEXT NOT NULL,reason TEXT NOT NULL,capabilities_json TEXT NOT NULL DEFAULT '[]',approval_required INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);`)}
export function decideAdaptive(ctx:SecurityContext,feedback:ExecutionFeedback):AdaptiveDecision{let action:NextAction='stop';let reason=feedback.reason||'execution completed';let capabilities=feedback.recommendedCapabilities??[];if(!feedback.ok){if(feedback.retryable){action='retry';reason='task reported a retryable failure';}else action='stop';}else if((feedback.findingCount??0)>0||capabilities.length){action='branch';reason='validated result produced findings or additional capabilities';}else action='continue';const risk:RiskLevel=feedback.findingCount&&feedback.findingCount>0?'medium':'low';const policy=riskDecision({...ctx,risk});if(policy==='deny'){action='stop';reason='policy denied adaptive continuation';capabilities=[];}const approvalRequired=action==='branch'&&riskDecision({...ctx,risk:'high'})==='approval_required';if(approvalRequired)action='approval_required';const id=randomId();getDb().prepare('INSERT INTO adaptive_decisions(id,mission_id,task_id,action,reason,capabilities_json,approval_required,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,feedback.missionId,feedback.taskId,action,reason,JSON.stringify(capabilities),approvalRequired?1:0,nowIso());audit(ctx.actor,'execution.adaptive.decision',feedback.taskId,'allow',{missionId:feedback.missionId,action,approvalRequired,capabilities});return {id,action,reason,capabilities,approvalRequired};}
export function recordFeedback(ctx:SecurityContext,feedback:ExecutionFeedback){const id=randomId();getDb().prepare('INSERT INTO execution_feedback(id,task_id,mission_id,ok,status,finding_count,evidence_count,retryable,recommended_json,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,feedback.taskId,feedback.missionId,feedback.ok?1:0,feedback.status,feedback.findingCount??0,feedback.evidenceCount??0,feedback.retryable?1:0,JSON.stringify(feedback.recommendedCapabilities??[]),feedback.reason??'',nowIso());return decideAdaptive(ctx,feedback);}
