import { getDb, randomId, nowIso } from './db';
import { audit, riskDecision, type SecurityContext, type RiskLevel } from './security';
import { routeCapability } from './capabilities';

export interface AgentProfile { id:string; name:string; provider:string; capabilities:string[]; enabled:boolean; }
type AgentRouteRow={id:string;name:string;provider:string};
export function initAgentRouterSchema(){getDb().exec(`CREATE TABLE IF NOT EXISTS agent_capabilities (agent_id TEXT NOT NULL, capability TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 100, enabled INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(agent_id,capability)); CREATE TABLE IF NOT EXISTS routing_decisions (id TEXT PRIMARY KEY, actor TEXT NOT NULL, capability TEXT NOT NULL, agent_id TEXT NOT NULL, provider TEXT, tool TEXT, decision TEXT NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL);`)}
export function registerAgentCapabilities(ctx:SecurityContext,agentId:string,capabilities:string[]){if(ctx.role!=='admin') throw new Error('admin role required'); const db=getDb(); for(const capability of capabilities) db.prepare('INSERT OR REPLACE INTO agent_capabilities(agent_id,capability,priority,enabled) VALUES(?,?,100,1)').run(agentId,capability); audit(ctx.actor,'agent.capabilities.registered',agentId,'allow',{capabilities});}
export function routeAgent(ctx:SecurityContext,capability:string,target?:string,risk?:RiskLevel){const agents=getDb().prepare(`SELECT a.id,a.name,a.provider FROM agents a JOIN agent_capabilities c ON c.agent_id=a.id WHERE c.capability=? AND c.enabled=1 ORDER BY c.priority ASC`).all(capability) as AgentRouteRow[]; if(!agents.length) throw new Error('no agent supports capability'); const tool=routeCapability(ctx,{capability,target,risk,projectId:ctx.projectId}); const selected=agents[0]; const decision=riskDecision({...ctx,target,risk:risk??'low',tool:tool.tool}); if(decision==='deny') throw new Error('policy denied agent route'); const id=randomId(); getDb().prepare('INSERT INTO routing_decisions(id,actor,capability,agent_id,provider,tool,decision,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,ctx.actor,capability,selected.id,selected.provider,tool.tool,decision,'capability and policy match',nowIso()); audit(ctx.actor,'agent.route',selected.id,'allow',{capability,provider:selected.provider,tool:tool.tool,approvalRequired:decision==='approval_required'}); return {...selected,tool:tool.tool,toolProvider:tool.provider,approvalRequired:decision==='approval_required',routingDecisionId:id}; }
