import {getDb,nowIso,randomId} from './db';import {audit,type SecurityContext} from './security';
export type AgentState='idle'|'busy'|'offline'|'quarantined';
export interface AgentRegistration{id:string;name:string;role:string;capabilities:string[];maxConcurrent?:number;}
export interface Handoff{taskId:string;fromAgent:string;toAgent?:string;kind:'result'|'request'|'conflict';payload:unknown;}
export function initAgentCoordinationSchema(){getDb().exec(`CREATE TABLE IF NOT EXISTS coordinated_agents(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'idle',capabilities_json TEXT NOT NULL DEFAULT '[]',max_concurrent INTEGER NOT NULL DEFAULT 1,last_heartbeat TEXT NOT NULL);CREATE TABLE IF NOT EXISTS task_leases(task_id TEXT PRIMARY KEY,agent_id TEXT NOT NULL,lease_until TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS agent_handoffs(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,from_agent TEXT NOT NULL,to_agent TEXT,kind TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL);`)}
export function registerAgent(ctx:SecurityContext,a:AgentRegistration){getDb().prepare(`INSERT INTO coordinated_agents(id,name,role,state,capabilities_json,max_concurrent,last_heartbeat) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,capabilities_json=excluded.capabilities_json,max_concurrent=excluded.max_concurrent,last_heartbeat=excluded.last_heartbeat,state='idle'`).run(a.id,a.name,a.role,'idle',JSON.stringify(a.capabilities??[]),a.maxConcurrent??1,nowIso());audit(ctx.actor,'agent.registered',a.id,'allow',{role:a.role,capabilities:a.capabilities??[]});return a;}
export function heartbeat(ctx:SecurityContext,id:string){const r=getDb().prepare('UPDATE coordinated_agents SET last_heartbeat=?,state=CASE WHEN state=\'offline\' THEN \'idle\' ELSE state END WHERE id=?').run(nowIso(),id);if(!r.changes)throw new Error('agent not registered');audit(ctx.actor,'agent.heartbeat',id,'allow');}
export function leaseTask(ctx:SecurityContext,taskId:string,agentId:string,seconds=60){const db=getDb();const a:any=db.prepare('SELECT * FROM coordinated_agents WHERE id=?').get(agentId);if(!a||a.state==='quarantined'||a.state==='offline')throw new Error('agent unavailable');const until=new Date(Date.now()+Math.max(5,Math.min(seconds,3600))*1000).toISOString();db.prepare('INSERT INTO task_leases(task_id,agent_id,lease_until,created_at) VALUES(?,?,?,?) ON CONFLICT(task_id) DO UPDATE SET agent_id=excluded.agent_id,lease_until=excluded.lease_until').run(taskId,agentId,until,nowIso());db.prepare("UPDATE coordinated_agents SET state='busy',last_heartbeat=? WHERE id=?").run(nowIso(),agentId);audit(ctx.actor,'task.leased',taskId,'allow',{agentId,leaseUntil:until});return {taskId,agentId,leaseUntil:until};}
export function handoff(ctx:SecurityContext,h:Handoff){const id=randomId();getDb().prepare('INSERT INTO agent_handoffs(id,task_id,from_agent,to_agent,kind,payload_json,created_at) VALUES(?,?,?,?,?,?,?)').run(id,h.taskId,h.fromAgent,h.toAgent??null,h.kind,JSON.stringify(h.payload),nowIso());audit(ctx.actor,'agent.handoff',h.taskId,'allow',{fromAgent:h.fromAgent,toAgent:h.toAgent,kind:h.kind});return {id,...h};}
