import {getDb,nowIso,randomId} from './db';import {audit,type SecurityContext,RiskLevel} from './security';
export type ApprovalStatus='pending'|'approved'|'rejected'|'expired'|'revoked';
export interface ApprovalRequest{missionId:string;taskId?:string;agentId?:string;tool?:string;target?:string;risk:RiskLevel;reason:string;expiresInSeconds?:number;}
const rank:Record<RiskLevel,number>={low:0,medium:1,high:2,critical:3};
export function initApprovalQueueSchema(){getDb().exec(`CREATE TABLE IF NOT EXISTS approval_requests(id TEXT PRIMARY KEY,mission_id TEXT NOT NULL,task_id TEXT,agent_id TEXT,tool TEXT,target TEXT,risk TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',requested_by TEXT NOT NULL,decided_by TEXT,decision_note TEXT,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,decided_at TEXT);CREATE INDEX IF NOT EXISTS idx_approval_status ON approval_requests(status);`)}
function expiry(s:number){return new Date(Date.now()+Math.max(30,Math.min(s,86400))*1000).toISOString();}
export function requestApproval(ctx:SecurityContext,r:ApprovalRequest){if(!r.missionId||!r.reason)throw new Error('missionId and reason are required');if(!r.tool||!r.target)throw new Error('tool and target are required for governed approval');const id=randomId(),exp=expiry(r.expiresInSeconds??900);getDb().prepare(`INSERT INTO approval_requests(id,mission_id,task_id,agent_id,tool,target,risk,reason,status,requested_by,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,r.missionId,r.taskId??null,r.agentId??null,r.tool,r.target,r.risk,r.reason,'pending',ctx.actor,nowIso(),exp);audit(ctx.actor,'approval.requested',id,'approval_required',{missionId:r.missionId,taskId:r.taskId,agentId:r.agentId,risk:r.risk,tool:r.tool,target:r.target});return {id,status:'pending',expiresAt:exp};}
export function decideApproval(ctx:SecurityContext,id:string,status:'approved'|'rejected'|'revoked',note=''){if(!['approved','rejected','revoked'].includes(status))throw new Error('invalid approval decision');const db=getDb();const row:any=db.prepare('SELECT * FROM approval_requests WHERE id=?').get(id);if(!row)throw new Error('approval not found');if(row.status!=='pending')throw new Error(`approval is ${row.status}`);if(new Date(row.expires_at).getTime()<Date.now()){db.prepare("UPDATE approval_requests SET status='expired' WHERE id=?").run(id);throw new Error('approval expired');}db.prepare('UPDATE approval_requests SET status=?,decided_by=?,decision_note=?,decided_at=? WHERE id=?').run(status,ctx.actor,note,nowIso(),id);audit(ctx.actor,`approval.${status}`,id,status==='approved'?'allow':'deny',{missionId:row.mission_id,taskId:row.task_id,agentId:row.agent_id,tool:row.tool,target:row.target,risk:row.risk});return {id,status};}
export function requireApproval(id:string){const row:any=getDb().prepare('SELECT * FROM approval_requests WHERE id=?').get(id);if(!row)throw new Error('approval not found');if(row.status!=='approved')throw new Error(`approval ${row.status}`);if(new Date(row.expires_at).getTime()<Date.now()){getDb().prepare("UPDATE approval_requests SET status='expired' WHERE id=?").run(id);throw new Error('approval expired');}return row;}
export function requireApprovedApproval(id:string,ctx:SecurityContext,missionId?:string,taskId?:string,agentId?:string){const row:any=requireApproval(id);if(!missionId||row.mission_id!==missionId)throw new Error('approval mission mismatch');if((taskId??null)!==(row.task_id??null))throw new Error('approval task mismatch');if((agentId??null)!==(row.agent_id??null))throw new Error('approval agent mismatch');if((ctx.tool??null)!==(row.tool??null))throw new Error('approval tool mismatch');if((ctx.target??null)!==(row.target??null))throw new Error('approval target mismatch');if(ctx.risk&&rank[ctx.risk]>rank[row.risk as RiskLevel])throw new Error('approval risk is insufficient for requested execution');audit(ctx.actor,'approval.consumed',id,'approved',{missionId:row.mission_id,taskId:row.task_id,agentId:row.agent_id,tool:row.tool,target:row.target,risk:row.risk});return row;}
