import { getDb, randomId, nowIso } from './db';
import { audit, requirePermission, riskDecision, type RiskLevel, type SecurityContext } from './security';

export interface CapabilityInput { name:string; description?:string; provider:string; tool:string; permission:string; risk?:RiskLevel; readOnly?:boolean; mitre?:string[]; }
export interface RouteRequest { capability:string; target?:string; risk?:RiskLevel; projectId?:string; }

export function initCapabilitySchema(){getDb().exec(`CREATE TABLE IF NOT EXISTS capability_catalog (id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',provider TEXT NOT NULL,tool TEXT NOT NULL,permission TEXT NOT NULL,risk TEXT NOT NULL DEFAULT 'low',read_only INTEGER NOT NULL DEFAULT 0,mitre_json TEXT NOT NULL DEFAULT '[]',enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,UNIQUE(provider,tool)); CREATE INDEX IF NOT EXISTS idx_capability_name ON capability_catalog(name);`)}

export function registerCapability(ctx:SecurityContext,input:CapabilityInput){requirePermission(ctx,'tools.manage'); if(!input.name||!input.provider||!input.tool||!input.permission) throw new Error('name, provider, tool and permission are required'); const id=randomId(); getDb().prepare(`INSERT INTO capability_catalog(id,name,description,provider,tool,permission,risk,read_only,mitre_json,enabled,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(provider,tool) DO UPDATE SET name=excluded.name,description=excluded.description,permission=excluded.permission,risk=excluded.risk,read_only=excluded.read_only,mitre_json=excluded.mitre_json,enabled=1`).run(id,input.name,input.description??'',input.provider,input.tool,input.permission,input.risk??'low',input.readOnly?1:0,JSON.stringify(input.mitre??[]),1,nowIso()); audit(ctx.actor,'capability.registered',input.tool,'allow',{provider:input.provider,name:input.name}); return id; }

export function listCapabilities(){return getDb().prepare('SELECT * FROM capability_catalog WHERE enabled=1 ORDER BY name,provider').all().map((r:any)=>({...r,readOnly:Boolean(r.read_only),mitre:JSON.parse(r.mitre_json||'[]')}));}

export function routeCapability(ctx:SecurityContext,req:RouteRequest){ const candidates=getDb().prepare('SELECT * FROM capability_catalog WHERE enabled=1 AND name=? ORDER BY CASE risk WHEN ? THEN 0 ELSE 1 END,read_only DESC').all(req.capability,req.risk??'low') as any[]; if(!candidates.length) throw new Error('no enabled capability provider'); const allowed=[]; for(const c of candidates){ const risk=(req.risk??c.risk) as RiskLevel; const decision=riskDecision({...ctx,projectId:req.projectId??ctx.projectId,target:req.target,risk,tool:c.tool}); if(decision!=='deny') allowed.push({provider:c.provider,tool:c.tool,risk:c.risk,readOnly:Boolean(c.read_only),approvalRequired:decision==='approval_required',mitre:JSON.parse(c.mitre_json||'[]')}); } if(!allowed.length) throw new Error('policy denied all capability providers'); const selected=allowed[0]; audit(ctx.actor,'capability.routed',selected.tool,'allow',{capability:req.capability,provider:selected.provider,target:req.target,approvalRequired:selected.approvalRequired}); return selected; }
