import { createHash } from 'node:crypto';
import { getDb, nowIso, randomId } from './db';
import { audit } from './security';

export function initEvidenceSchema():void{getDb().exec(`CREATE TABLE IF NOT EXISTS security_evidence(id TEXT PRIMARY KEY,mission_id TEXT,task_id TEXT,kind TEXT NOT NULL,name TEXT NOT NULL,content_hash TEXT NOT NULL,metadata TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS evidence_custody(id TEXT PRIMARY KEY,evidence_id TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '{}',previous_hash TEXT,event_hash TEXT NOT NULL,created_at TEXT NOT NULL);`);}
export function addEvidence(actor:string,input:{missionId?:string;taskId?:string;kind:string;name:string;content:string|Buffer;metadata?:Record<string,unknown>}):string{const id=randomId(),ts=nowIso(),hash=createHash('sha256').update(input.content).digest('hex');getDb().prepare('INSERT INTO security_evidence(id,mission_id,task_id,kind,name,content_hash,metadata,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,input.missionId??null,input.taskId??null,input.kind,input.name,hash,JSON.stringify(input.metadata??{}),actor,ts);appendCustody(id,actor,'created',{hash});audit(actor,'evidence.created',id,'allow',{hash});return id;}
export function appendCustody(evidenceId:string,actor:string,action:string,detail:unknown={}):void{const db=getDb();const prev=db.prepare('SELECT event_hash FROM evidence_custody WHERE evidence_id=? ORDER BY created_at DESC LIMIT 1').get(evidenceId) as {event_hash:string}|undefined;const ts=nowIso();const payload=JSON.stringify({evidenceId,actor,action,detail,previous_hash:prev?.event_hash??null,ts});const eventHash=createHash('sha256').update(payload).digest('hex');db.prepare('INSERT INTO evidence_custody(id,evidence_id,actor,action,detail,previous_hash,event_hash,created_at) VALUES (?,?,?,?,?,?,?,?)').run(randomId(),evidenceId,actor,action,JSON.stringify(detail),prev?.event_hash??null,eventHash,ts);}
export function getEvidence(id:string):unknown{const e=getDb().prepare('SELECT * FROM security_evidence WHERE id=?').get(id);if(!e)throw new Error('evidence not found');return {...e as object,custody:getDb().prepare('SELECT * FROM evidence_custody WHERE evidence_id=? ORDER BY created_at').all(id)};}
