import { getDb, nowIso, randomId } from './db';
import { audit } from './security';
import { mapFinding, techniquesForFinding } from './mitre';

export type FindingStatus='open'|'validated'|'rejected'|'closed';
export function initFindingsSchema():void{getDb().exec(`CREATE TABLE IF NOT EXISTS security_findings(id TEXT PRIMARY KEY,mission_id TEXT,task_id TEXT,title TEXT NOT NULL,description TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'info',confidence REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'open',evidence_id TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_findings_mission ON security_findings(mission_id);`);}
export function createFinding(actor:string,input:{missionId?:string;taskId?:string;title:string;description:string;severity?:string;confidence?:number;evidenceId?:string;techniques?:{id:string;confidence?:number}[]}):string{const id=randomId(),ts=nowIso();getDb().prepare('INSERT INTO security_findings(id,mission_id,task_id,title,description,severity,confidence,status,evidence_id,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(id,input.missionId??null,input.taskId??null,input.title,input.description,input.severity??'info',Math.max(0,Math.min(1,input.confidence??0)),'open',input.evidenceId??null,actor,ts,ts);for(const t of input.techniques??[])mapFinding(id,t.id,t.confidence??input.confidence??0,actor);audit(actor,'finding.created',id,'allow',{severity:input.severity??'info'});return id;}
export function validateFinding(actor:string,id:string,valid:boolean,confidence?:number):void{const status:FindingStatus=valid?'validated':'rejected';getDb().prepare('UPDATE security_findings SET status=?,confidence=COALESCE(?,confidence),updated_at=? WHERE id=?').run(status,confidence??null,nowIso(),id);audit(actor,'finding.validation',id,valid?'allow':'deny',{confidence});}
export function listFindings():unknown[]{return getDb().prepare('SELECT * FROM security_findings ORDER BY created_at DESC').all().map((f:any)=>({...f,techniques:techniquesForFinding(f.id)}));}
