import { getDb, nowIso, randomId } from './db';
import { audit } from './security';
export function initScopeSchema():void{getDb().exec(`CREATE TABLE IF NOT EXISTS security_assets(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,value TEXT NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_security_assets_project ON security_assets(project_id);`);}
export function createProject(actor:string,name:string,description=''):string{const id=randomId();getDb().prepare('INSERT INTO security_projects(id,name,description,created_at) VALUES (?,?,?,?)').run(id,name,description,nowIso());audit(actor,'project.created',id,'allow',{name});return id;}
export function addScope(actor:string,projectId:string,kind:string,value:string,excluded=false):string{const id=randomId();getDb().prepare('INSERT INTO security_scopes(id,project_id,kind,value,excluded,created_at) VALUES (?,?,?,?,?,?)').run(id,projectId,kind,value,excluded?1:0,nowIso());audit(actor,'scope.created',id,'allow',{projectId,kind,value,excluded});return id;}
export function listProjects():unknown[]{return getDb().prepare('SELECT * FROM security_projects ORDER BY created_at DESC').all();}
export function listScopes(projectId:string):unknown[]{return getDb().prepare('SELECT * FROM security_scopes WHERE project_id=? ORDER BY created_at').all(projectId);}
function matches(kind:string,value:string,target:string):boolean{if(kind==='exact')return target===value;if(kind==='hostname')return target===value||target.endsWith('.'+value);if(kind==='cidr')return target===value;return target.includes(value);}
export function targetInScope(projectId:string|undefined,target:string|undefined):boolean{if(!projectId)return !target; if(!target)return true;const rows=getDb().prepare('SELECT kind,value,excluded FROM security_scopes WHERE project_id=?').all(projectId) as {kind:string;value:string;excluded:number}[];if(rows.length===0)return false;if(rows.some(r=>r.excluded&&matches(r.kind,r.value,target)))return false;return rows.some(r=>!r.excluded&&matches(r.kind,r.value,target));}
export function assertTargetInScope(actor:string,projectId:string|undefined,target:string|undefined):void{if(!targetInScope(projectId,target)){audit(actor,'scope.violation',target||'unspecified','deny',{projectId,target});throw new Error('target is outside the declared project scope');}}
