import { getDb, nowIso, randomId } from './db';
import { audit, requireApprovedApproval, riskDecision, type SecurityContext } from './security';
import { GovernedMcpAdapter, type McpProvider } from './mcp-adapters';

export interface WorkerOptions { pollMs?:number; concurrency?:number; }
export class TaskWorker {
  private timer?:NodeJS.Timeout; private active=0;
  constructor(private readonly adapter=new GovernedMcpAdapter(),private readonly options:WorkerOptions={}){}
  start(){if(this.timer) return; const poll=this.options.pollMs??1000; this.timer=setInterval(()=>void this.tick(),poll); void this.tick();}
  stop(){if(this.timer) clearInterval(this.timer); this.timer=undefined;}
  private async tick(){const limit=this.options.concurrency??2;if(this.active>=limit)return; const db=getDb(); const rows:any[]=db.prepare(`SELECT t.*,m.created_by FROM security_mission_tasks t JOIN security_missions m ON m.id=t.mission_id WHERE t.status='queued' ORDER BY t.created_at ASC LIMIT ?`).all(limit-this.active); for(const row of rows){this.active++; void this.run(row).finally(()=>this.active--);}}
  private async run(row:any){const db=getDb(); const ctx:SecurityContext={actor:row.created_by||'worker',role:'admin',projectId:undefined,target:row.target||undefined,risk:row.risk,tool:row.tool||undefined}; try{if(row.approval_id) requireApprovedApproval(row.approval_id,ctx); const decision=riskDecision(ctx); if(decision==='deny') throw new Error('policy denied task at execution time'); db.prepare(`UPDATE security_mission_tasks SET status='running',updated_at=? WHERE id=? AND status='queued'`).run(nowIso(),row.id); audit(ctx.actor,'task.started',row.id,'allow',{missionId:row.mission_id}); if(!row.tool){db.prepare(`UPDATE security_mission_tasks SET status='completed',result=?,updated_at=? WHERE id=?`).run(JSON.stringify({mode:'orchestration-only'}),nowIso(),row.id);return;} const provider=this.resolveProvider(row.tool); const result=await this.adapter.invoke(ctx,provider,row.tool,{}); const status=result.ok?'completed':'failed'; db.prepare(`UPDATE security_mission_tasks SET status=?,result=?,updated_at=? WHERE id=?`).run(status,JSON.stringify(result),nowIso(),row.id); audit(ctx.actor,'task.completed',row.id,result.ok?'allow':'deny',{provider:provider.id,tool:row.tool}); }catch(e){db.prepare(`UPDATE security_mission_tasks SET status='failed',result=?,updated_at=? WHERE id=?`).run(JSON.stringify({error:String((e as Error).message)}),nowIso(),row.id);audit(ctx.actor,'task.failed',row.id,'deny',{error:String((e as Error).message)});}}
  private resolveProvider(tool:string):McpProvider{const row:any=getDb().prepare(`SELECT provider FROM capability_catalog WHERE tool=? AND enabled=1 ORDER BY read_only DESC LIMIT 1`).get(tool);if(!row)throw new Error('no MCP provider registered for tool'); const p:any=getDb().prepare(`SELECT id,name,kind,endpoint,enabled FROM mcp_servers WHERE id=?`).get(row.provider);if(!p)throw new Error(`MCP provider '${row.provider}' is not registered`);return {id:p.id,name:p.name,kind:p.kind,endpoint:p.endpoint,enabled:Boolean(p.enabled)};}
}
