import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {apiGet,apiPost} from '../api';

type Provider={id:string;name:string;endpoint:string;kind:string;enabled:number|boolean;healthStatus?:string;lastCheckedAt?:string;latencyMs?:number;toolCount?:number;error?:string|null};
type Approval={id:string;project_id?:string;actor:string;tool:string;target?:string;risk:string;request:string;status:string;created_at:string;expires_at?:string};
type Finding={id:string;mission_id?:string;title:string;severity:string;confidence:number;status:string;created_at:string;techniques?:{technique_id?:string;id?:string;confidence?:number}[]};
type Technique={id:string;name:string;tactic?:string};
type Health={ok:boolean;name:string;time:string;[key:string]:unknown};

const riskRank:Record<string,number>={low:1,medium:2,high:3,critical:4};

export default function OperatorConsole(){
 const [health,setHealth]=useState<Health|null>(null); const [providers,setProviders]=useState<Provider[]>([]); const [approvals,setApprovals]=useState<Approval[]>([]); const [findings,setFindings]=useState<Finding[]>([]); const [techniques,setTechniques]=useState<Technique[]>([]); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState('');
 const load=useCallback(async()=>{try{setError('');const [h,p,a,f,t]=await Promise.all([apiGet<Health>('/api/health'),apiGet<{providers:Provider[]}>('/api/mcp/providers'),apiGet<{approvals:Approval[]}>('/api/security-platform/approvals'),apiGet<{findings:Finding[]}>('/api/intelligence/findings'),apiGet<{techniques:Technique[]}>('/api/intelligence/techniques')]);setHealth(h);setProviders(p.providers||[]);setApprovals(a.approvals||[]);setFindings(f.findings||[]);setTechniques(t.techniques||[]);}catch(e){setError(String((e as Error).message));}},[]);
 useEffect(()=>{load();const timer=window.setInterval(load,8000);return()=>window.clearInterval(timer)},[load]);
 const resolve=async(id:string,decision:'approved'|'denied')=>{setBusy(id);try{await apiPost(`/api/security-platform/approvals/${encodeURIComponent(id)}`,{decision,reason:`Operator console: ${decision}`});await load();}catch(e){setError(String((e as Error).message))}finally{setBusy(null)}};
 const pending=approvals.filter(a=>a.status==='pending'); const openFindings=findings.filter(f=>f.status==='open'); const healthy=providers.filter(p=>p.healthStatus==='healthy'||p.healthStatus==='ok').length;
 const mapped=new Set(findings.flatMap(f=>(f.techniques||[]).map(t=>t.technique_id||t.id).filter(Boolean) as string[])); const coverage=techniques.length?Math.round(mapped.size/techniques.length*100):0;
 const criticalPending=useMemo(()=>pending.filter(a=>(riskRank[a.risk]||0)>=3).length,[pending]);
 return <div className="p-6 space-y-6">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-widest text-accent">Phase 5 · Operator Experience</div><h1 className="mt-1 text-2xl font-bold text-white">Security Mission Console</h1><p className="mt-1 text-sm text-slate-400">Governed approvals, provider health and intelligence in one operator surface.</p></div><div className="flex items-center gap-3"><span className="rounded-full border border-ink-600 bg-ink-900 px-3 py-1.5 text-xs text-slate-300"><span className={`mr-2 inline-block h-2 w-2 rounded-full ${health?.ok?'bg-emerald-400':'bg-amber-400'}`}/>{health?.ok?'control plane healthy':'control plane unavailable'}</span><button onClick={load} className="rounded-lg border border-ink-600 bg-ink-900 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:border-ink-500">Refresh</button></div></header>
  {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat title="Pending approvals" value={pending.length}/><Stat title="High/Critical pending" value={criticalPending}/><Stat title="Open findings" value={openFindings.length}/><Stat title="Providers healthy" value={`${healthy}/${providers.length}`}/><Stat title="ATT&CK mapped" value={`${coverage}%`}/></section>
  <section className="grid gap-5 xl:grid-cols-[1.4fr_1fr]">
   <Panel title="Human approval center" subtitle="Execution authority remains with the governed approval queue.">{pending.length===0?<Empty text="No pending approvals."/>:<div className="divide-y divide-ink-800">{pending.slice(0,12).map(a=><div key={a.id} className="px-5 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-sm font-semibold text-white">{a.tool}</div><div className="mt-1 text-xs text-slate-500">{a.target||'target unspecified'} · requested by {a.actor}</div><div className="mt-2 text-xs text-slate-400">{a.request?.slice(0,180)}</div></div><span className={`rounded-full px-2 py-1 text-[10px] uppercase tracking-wider ${a.risk==='critical'?'bg-red-500/10 text-red-300':a.risk==='high'?'bg-orange-500/10 text-orange-300':'bg-amber-500/10 text-amber-300'}`}>{a.risk}</span></div><div className="mt-3 flex gap-2"><button disabled={busy===a.id} onClick={()=>resolve(a.id,'approved')} className="rounded-md bg-emerald-500/15 px-3 py-1.5 text-xs font-semibold text-emerald-300 hover:bg-emerald-500/25 disabled:opacity-50">Approve</button><button disabled={busy===a.id} onClick={()=>resolve(a.id,'denied')} className="rounded-md bg-red-500/10 px-3 py-1.5 text-xs font-semibold text-red-300 hover:bg-red-500/20 disabled:opacity-50">Deny</button></div></div>)}</div>}</Panel>
   <Panel title="MCP provider health" subtitle="Kali and HexStrike remain behind the governed gateway."><div className="space-y-3">{providers.length===0?<Empty text="No configured MCP providers."/>:providers.map(p=><div key={p.id} className="rounded-lg border border-ink-700 bg-ink-950/60 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${p.healthStatus==='healthy'||p.healthStatus==='ok'?'bg-emerald-400':p.healthStatus==='degraded'?'bg-amber-400':'bg-red-400'}`}/><span className="text-sm font-semibold text-white">{p.name}</span></div><span className="text-[10px] uppercase tracking-wider text-slate-500">{p.kind}</span></div><div className="mt-2 flex gap-4 text-xs text-slate-500"><span>{p.toolCount??0} tools</span><span>{p.latencyMs??'—'} ms</span><span>{p.enabled?'enabled':'disabled'}</span></div>{p.error&&<div className="mt-2 text-xs text-red-300">{p.error}</div>}</div>)}</div></Panel>
  </section>
  <section className="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
   <Panel title="Finding explorer" subtitle="Analyst-facing intelligence produced from governed execution results."><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="px-5 py-3">Finding</th><th className="px-3 py-3">Severity</th><th className="px-3 py-3">Confidence</th><th className="px-3 py-3">Status</th></tr></thead><tbody className="divide-y divide-ink-800">{findings.slice(0,12).map(f=><tr key={f.id}><td className="px-5 py-3"><div className="font-medium text-white">{f.title}</div><div className="mt-1 text-[10px] text-slate-600">{f.mission_id||'unscoped mission'} · {f.id}</div></td><td className="px-3 py-3 uppercase text-slate-300">{f.severity}</td><td className="px-3 py-3 text-slate-300">{Math.round(Number(f.confidence||0)*100)}%</td><td className="px-3 py-3"><span className="rounded-full bg-ink-800 px-2 py-1 text-[10px] text-slate-300">{f.status}</span></td></tr>)}</tbody></table>{findings.length===0&&<Empty text="No findings have been recorded."/>}</div></Panel>
   <Panel title="ATT&CK coverage" subtitle="Candidate mappings are advisory and never grant execution authority."><div className="mb-4 flex items-end justify-between"><div><div className="text-3xl font-bold text-white">{coverage}%</div><div className="text-xs text-slate-500">techniques represented by current findings</div></div><div className="text-right text-xs text-slate-500">{mapped.size}/{techniques.length}</div></div><div className="h-2 overflow-hidden rounded-full bg-ink-800"><div className="h-full rounded-full bg-accent" style={{width:`${coverage}%`}}/></div><div className="mt-4 flex flex-wrap gap-2">{Array.from(mapped).slice(0,12).map(id=><span key={id} className="rounded-md border border-ink-700 bg-ink-950 px-2 py-1 text-[10px] text-slate-400">{id}</span>)}</div></Panel>
  </section>
  <section className="grid gap-4 md:grid-cols-3"><Quick href="#/mission-control" title="Mission timeline" text="Replay approvals and audit activity by mission."/><Quick href="#/activity" title="Audit explorer" text="Review the control-plane event stream."/><Quick href="#/security" title="Security center" text="Inspect findings, evidence and platform controls."/></section>
 </div>
}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-xl border border-ink-700 bg-ink-900"><div className="border-b border-ink-700 px-5 py-4"><div className="font-semibold text-white">{title}</div><div className="mt-1 text-xs text-slate-500">{subtitle}</div></div>{children}</section>}
function Stat({title,value}:{title:string;value:React.ReactNode}){return <div className="rounded-xl border border-ink-700 bg-ink-900 p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{title}</div><div className="mt-2 text-2xl font-bold text-white">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="p-5 text-sm text-slate-500">{text}</div>}
function Quick({href,title,text}:{href:string;title:string;text:string}){return <a href={href} className="rounded-xl border border-ink-700 bg-ink-900 p-4 transition hover:border-ink-500"><div className="text-sm font-semibold text-white">{title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{text}</div></a>}
